server {
    server_name knowledgeparkguide.in www.knowledgeparkguide.in;
    root /var/www/knowledgeparkguide.in;
    index index.php;
    client_max_body_size 64M;

    location / { try_files $uri $uri/ /index.php?$args; }
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }
    location = /xmlrpc.php { deny all; }
    location ~ /\.(?!well-known) { deny all; }
    location ~* \.(css|js|jpg|jpeg|png|gif|webp|avif|svg|ico|woff2?)$ { expires 30d; access_log off; }

    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/knowledgeparkguide.in/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/knowledgeparkguide.in/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.knowledgeparkguide.in) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = knowledgeparkguide.in) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name knowledgeparkguide.in www.knowledgeparkguide.in;
    return 404; # managed by Certbot




}